### PR TITLE
Migrated to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@thiagoloureiro

**Comment by MarkCiliaVincenti** [comment]
@thiagoloureiro ?

**Comment by MarkCiliaVincenti** [comment]
@thiagoloureiro

**Comment by thiagoloureiro** [comment]
Hi Mark! Sorry I will take a look thanks for the contribution :)

**Comment by MarkCiliaVincenti** [comment]
> Hi Mark! Sorry I will take a look thanks for the contribution :)

Cheers :)

**Pull request merged**
