### PR TITLE
Using AsyncNonKeyedLocker on MemchachedNode

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by thiagoloureiro** [comment]
Hi @MarkCiliaVincenti , build is breaking.

https://ci.appveyor.com/project/thiagoloureiro/easymemorycache/builds/48949112

I also cloned your repo locally and broke it here.

image

**Comment by MarkCiliaVincenti** [comment]
Sorry I broke it. Let me try to fix it from my phone.

**Comment by MarkCiliaVincenti** [comment]
What about now @thiagoloureiro?

**Comment by MarkCiliaVincenti** [comment]
Pesky bug got me out of bed :) Should be OK now @thiagoloureiro

**Comment by MarkCiliaVincenti** [comment]
@thiagoloureiro works now

**Comment by thiagoloureiro** [comment]
grazzi hafna :)

**Comment by thiagoloureiro** [comment]
https://www.nuget.org/packages/EasyMemoryCache/2.0.1 published

**Pull request merged**
