### PR TITLE
Performance improvement for .NET 9.0+

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by thiagoloureiro** [comment]
Hi Mark thanks for the PR, I see the build is failing due to the .net 9 not being supported yet by the CI.
with those modifications applications with .net 8 will still work with that ?

**Comment by MarkCiliaVincenti** [comment]
Yes it will with no performance or memory allocation penalty but the locking would be faster for someone using your library on net9.

**Comment by MarkCiliaVincenti** [comment]
I tried to fix the CI but failed to do so. Not sure what needs to be done so that appveyor allows .NET 9.0.

**Comment by thiagoloureiro** [comment]
Hi Mark, is a limitation from appveyor, their agent doesn't have .net 9 yet, let me see other alternatives.

**Comment by thiagoloureiro** [comment]
Hi Mark,
https://www.nuget.org/packages/EasyMemoryCache/2.0.6
Grazzi ħafna :)

**Comment by MarkCiliaVincenti** [comment]
Hmm I'm not sure what language I should use to tell you "you're welcome" :)

Polish? Portuguese? Spanish? :)

**Comment by thiagoloureiro** [comment]
haha :) can be in maltese if you wish, I lived in Malta a few years in Xemxija, good times :) My native tongue is portuguese.
I dropped you an Linkedin invitation.

**Comment by MarkCiliaVincenti** [comment]
Wow that's cool. Obrigado. My LinkedIn is quite a few years out of date though :)

**Pull request merged**
